/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import org.junit.Assert;
import org.junit.Test;

public class MonsterTest {
  @Test
  public void testSummonMonster1() {
    Monster monster1 = new Monster(0, 0);
    Assert.assertEquals("キングデュラハン:レア度[3]\n", monster1.toString());
    Monster monster2 = new Monster(3, 3);
    Assert.assertEquals("キングデュラハン:レア度[3]\n", monster1.toString());
  }
}
