/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import java.util.LinkedList;
import java.util.Random;

public class App {
  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println();

    LinkedList<Integer> list = new LinkedList<>();
    LinkedList<Integer> list1 = new LinkedList<>();
    LinkedList<Integer> list2 = new LinkedList<>();

    Random rand = new Random();
    /* 勝敗用List */
    list.add(rand.nextInt(5));
    list.add(3);

    for (int i = 0; i < 5; i++) {
      list1.add(i);
      list1.add(i);
      list2.add(i);
      list2.add(i);
    }

    seMonsterGame gameTest = new seMonsterGame(list, list1, "player1", list2, "player2");
    System.out.println(gameTest.toString());
    System.out.println(gameTest.battle());
  }

}
